services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db-data: {}