spring:
  application:
    name: ${APP_NAME}
    jwt:
      secretKey: ${JWT_SECRET_KEY}

  server:
    port: ${SERVER_PORT}

  datasource:
    url: jdbc:${DB_CONNECTION}://${DB_HOST}:${DB_PORT}/postgres?currentSchema=${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show_sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      discovery:
        enabled: false
      base-path: /check
      path-mapping:
        health: /
      exposure:
        include: health