spring:

  application:
    name: ${APP_NAME}
    jwt:
      secretKey: ${JWT_SECRET_KEY}
      expiration-time: ${JWT_EXPIRATION_DELAY}

  server:
    port: ${SERVER_PORT}

  datasource:
    url: jdbc:${DB_CONNECTION}://${DB_HOST}:${DB_PORT}/persevero_db?currentSchema=v1
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: v1

management:
  endpoints:
    web:
      discovery:
        enabled: false
      base-path: /check
      path-mapping:
        health: /
      exposure:
        include: health